name = "company"
compatibility_date = "2024-09-09"
tsconfig = "tsconfig.app.json"
compatibility_flags = ["nodejs_compat"]

[vars]
MY_VAR = "my-variable"
NEON_DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/postgres"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"                                   # i.e. available in your Worker on env.DB
# database_name = "my-database"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"
