export const accessLogFormat = {
  requestTime: '$context.requestTime',
  requestId: '$context.requestId',
  httpMethod: '$context.httpMethod',
  path: '$context.path',
  routeKey: '$context.routeKey',
  status: '$context.status',
  responseLatency: '$context.responseLatency',
  integrationRequestId: '$context.integration.requestId',
  functionResponseStatus: '$context.integration.status',
  integrationLatency: '$context.integration.latency',
  integrationServiceStatus: '$context.integration.integrationStatus',
  authorizeResultStatus: '$context.authorizer.status',
  authorizerRequestId: '$context.authorizer.requestId',
  ip: '$context.identity.sourceIp',
  userAgent: '$context.identity.userAgent',
  principalId: '$context.authorizer.principalId',
  cognitoUser: '$context.identity.cognitoIdentityId',
  user: '$context.identity.user',
  caller: '$context.identity.caller',
  resourcePath: '$context.resourcePath',
  protocol: '$context.protocol',
  responseLength: '$context.responseLength',
};
