// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1UsersByIdData, GetApiV1UsersByIdResponse } from './types.gen';

export class UsersService {
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns GetUserResponse Success
     * @throws ApiError
     */
    public static getApiV1UsersById(data: GetApiV1UsersByIdData): CancelablePromise<GetApiV1UsersByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            },
            errors: {
                404: 'Not found',
                500: 'Internal server error'
            }
        });
    }
    
}