// This file is auto-generated by @hey-api/openapi-ts

export interface GetUserResponse {
    /**
     * The ID of the user
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The role of the user
     */
    role: 'admin' | 'customer';
    /**
     * The created at date of the user
     */
    createdAt: string;
    /**
     * The updated at date of the user
     */
    updatedAt: string;
}

/**
 * The role of the user
 */
export enum role {
    ADMIN = 'admin',
    CUSTOMER = 'customer'
}

export interface ErrorResponse {
    /**
     * The code of the error
     */
    code?: string;
    /**
     * The status code of the error
     */
    status: number;
    /**
     * The title of the error
     */
    title: string;
    /**
     * The detail of the error
     */
    detail: string;
    /**
     * The source of the error
     */
    source?: {
        pointer?: string;
        parameter?: string;
        header?: string;
    };
}

export interface GetApiV1UsersByIdData {
    id: string;
}

export type GetApiV1UsersByIdResponse = GetUserResponse;

export interface $OpenApiTs {
    '/api/v1/users/{id}': {
        get: {
            req: GetApiV1UsersByIdData;
            res: {
                /**
                 * Success
                 */
                200: GetUserResponse;
                /**
                 * Not found
                 */
                404: ErrorResponse;
                /**
                 * Internal server error
                 */
                500: ErrorResponse;
            };
        };
    };
}